# Generated by Django 4.2.4 on 2023-09-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('AccountId', models.AutoField(primary_key=True, serialize=False)),
                ('AccountNumber', models.IntegerField()),
                ('AccountType', models.CharField(max_length=255)),
                ('CustomerId', models.CharField(max_length=255)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=255)),
                ('CustomerPhone', models.CharField(max_length=20)),
                ('CustomerEmail', models.CharField(max_length=255)),
                ('CustomerAddress', models.CharField(max_length=255)),
                ('AccountNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=255)),
                ('EmployeePhone', models.CharField(max_length=20)),
                ('EmployeeEmail', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('AccountNumber', models.IntegerField()),
                ('TransactionDate', models.DateField()),
                ('TransactionType', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
    ]
